#####
# Docker compose YAML file
#
# For documentation see: https://docs.docker.com/compose/yml/
#####

version: "3"

volumes:
    psqldata: {}
    staticfiles:
    media-files:
    
    
services:
    real-db:
        image: postgres:10.1
        volumes:
            # - /opt/starter/psql:/var/lib/postgresql/data/pgdata
            - ./psqldata:/var/lib/postgresql/data/pgdata
        env_file:
            - ./config/environment/development.env

    webapp:
        build:
            context: webapp
        volumes:
            # - ./webapp/starter/staticfiles:/srv/static-files
            # - static-files:/srv/static-files
            - ./webapp/starter/staticfiles:/srv/starter/staticfiles
            - media-files:/srv/media-files
            - ./webapp/starter:/srv/starter
        expose:
            - "8000"
        depends_on:
            - real-db
        env_file:
            - ./config/environment/development.env
        restart: always

    webserver:
        build:
            context: .
            dockerfile: services/webserver/Dockerfile
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - webapp
        volumes:
            - ./webapp/starter/staticfiles:/srv/starter/staticfiles
            - media-files:/srv/media-files
        env_file:
            - ./config/environment/development.env
        restart: always
